#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Needed to make Starship prompt work.
# https://github.com/sorin-ionescu/prezto/issues/1887
setopt prompt_subst interactive_comments

# Set up fzf key bindings and fuzzy completion
source <(fzf --zsh)

# ASDF
. /opt/homebrew/opt/asdf/libexec/asdf.sh

# Setup zoxide for smart cd
eval "$(zoxide init zsh)"

# Aliases
alias reload="exec zsh"
alias v="nvim"
alias vi="nvim"

if [[ $OS = "Darwin" ]]; then
  # Path Shortcuts
  [ -f /usr/local/bin/trash ]; and alias rm="trash"

  # df
  alias df='df -hi'
fi

# Get my IP
alias myip="dig +short myip.opendns.com @resolver1.opendns.com"

# TMUX
alias t="tmux"
alias ta='tmux attach -t'
alias tls='tmux ls'
alias tns='tmux new -s'
alias tks='tmux kill-session -t'
alias tkill='tmux kill-server'

# History
alias h='history'
alias hm='history --merge'
alias ht='history --show-time'
alias hs='history | fzy'

# Cd
alias c="cd"

# Make dir
alias md='mkdir -p'
